server:
  AppVersion: 1.0.0
  Port: 9000
  Mode: dev
mysql:
  Host: localhost
  Port: 3306
  User: esportal-twitter
  Password: esportal-twitter-password
  DBname: twitter
  MaxOpenConns: 10
  MaxIdleConns: 10
  MaxLifetime: 5 #minutes
Logger:
  Level: debug
  Output: logs
  Formatter: text
